enum DB {
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
}

enum SENDGRID {
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  SENDGRID_FROM_EMAIL = 'SENDGRID_FROM_EMAIL',
}

enum GOOGLE {
  GOOGLE_GET_USER_INFO_URL = 'GOOGLE_GET_USER_INFO_URL',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_API_KEY = 'GOOGLE_API_KEY',
}

enum AWS {
  AWS_BUCKET_REGION = 'AWS_BUCKET_REGION',
  AWS_BUCKET_NAME = 'AWS_BUCKET_NAME',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_KEY = 'AWS_SECRET_KEY',
}

enum REDIS {
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
}

export const ConfigServiceKeys = {
  PORT: 'PORT',
  NODE_ENV: 'NODE_ENV',
  TIMEZONE: 'TIMEZONE',
  JWT_SECRET: 'JWT_SECRET',
  CLIENT_DOMAIN: 'CLIENT_DOMAIN',
  DOMAIN: 'DOMAIN',
  ...SENDGRID,
  ...DB,
  ...GOOGLE,
  ...AWS,
  ...REDIS,
} as const;

export type ConfigServiceType = typeof ConfigServiceKeys;
export const SALT_ROUNDS = 10;
